language: python
python:
  - "3.9"

before_script:
  - pip3 install pipenv
  - pipenv install

env:
  - DJANGO_SETTINGS_MODULE="pur_beurre.settings.travis"
  -

services:
  - postgresql

script:
  - pytest
